services:
  nginx:
    image: nginx:1.12.0
    container_name: "nginx"
    restart: "always"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - api
      - app

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: "app"
    env_file: ./environments/app.env
    volumes:
      - upload-data:/usr/src/app/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: "api"
    env_file: ./environments/api.env
    volumes:
      - upload-data:/usr/src/app/data
    depends_on:
      database:
        condition: service_healthy

  database:
      container_name: "database"
      image: postgres:16
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 1s
        timeout: 5s
        retries: 10
      env_file: ./environments/postgres.env
      ports:
        - 5432:5432
      volumes:
        - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/postgres'

  upload-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './data/upload'
